### ISSUE TITLE
Support for XCB Surfaces missing

### ISSUE THREAD

**Issue by HugoOsornio** [PacktPublishing/Learning-Vulkan#1]
Hello guys!

I just checked on Chapter 3 and the CMakeLists.txt assumes that we are using Windows and does not consider a Linux Build System or target.

**# Add any required preprocessor definitions here
add_definitions(-DVK_USE_PLATFORM_WIN32_KHR)**

However, that define is not used, in the code you force the extension names to be WIN32.

**std::vector<const char *> instanceExtensionNames = {
	VK_KHR_SURFACE_EXTENSION_NAME,
	VK_KHR_WIN32_SURFACE_EXTENSION_NAME
};**
 
I think an option to include:
VK_KHR_XCB_SURFACE_EXTENSION_NAME
or
VK_KHR_ANDROID_SURFACE_EXTENSION_NAME 
should be included.

**Comment by MurtazaTinwala** [comment]
Hi Hugo, 

This is the reply from the author to your mail: 

Well, this book contains the examples that are only meant for Windows platform for now. In future, we may support it on Linux or Android. 

Regards , 
Murtaza Tinwala 
Technical Editor — Content 
Packt> 
Skype: packt.murtazat | Hangouts: murtazat.packt@gmail.com | Mob: +91 9619533577 | www.packtpub.com Packt Publishing Private Limited. Registered Address: Plot No. 103, Arena House, 3rd Floor, Road No.12, Opp. Goldfinch Hotel, MIDC, Andheri East, Mumbai 400093. CIN:U22100MH2005PTC152766 
This E-mail is confidential. It may also be legally privileged. If you are not the addressee you may not copy, forward, disclose or use any part of it. If you have received this message in error, please delete it and all copies from your system and notify the sender immediately by return E-mail. Whilst Packt Publishing Ltd take every reasonable precaution to avoid the transfer of software viruses or defects that may cause damage to computer systems; it is the responsibility of the recipient to ensure that all emails and attachments received are free from infection.
