### ISSUE TITLE
it is not allowed to transition swapchain image without first acquiring them.

### ISSUE THREAD

**Issue by ratchetfreak** [PacktPublishing/Learning-Vulkan#2]
https://github.com/PacktPublishing/Learning-Vulkan/blob/ac20fda89da435583ac076d16f2ff89f24580cda/Chapter%2002/HelloWorld_psedocode.cpp#L147

what you should instead do is always assume the image is UNDEFINED when starting the render.

In particular you can set the sourceLayout in the renderpass to UNDEFINED especially when using VK_ATTACHMENT_LOAD_OP_CLEAR or DONT_CARE

**Comment by packt-pradeeps** [comment]
Please reopen the issue if it still persists.
