### ISSUE TITLE
find_package(Vulkan) should come after project()

### ISSUE THREAD

**Issue by FusionOpz** [PacktPublishing/Learning-Vulkan#4]
I've been encountering an issue while following the book where CMake is unable to find and set `Vulkan_LIBRARY`, the workaround that I found that works is to set the project name BEFORE the auto-locate block of code in the CMakeLists.txt file.  CMake needs to be able to check for bit-ness before `Vulkan_FOUND` is set to true.

I'm running the latest release of CMake 3.18 on Windows 10 Pro 2004.

The other thing is we should be using `target_link_libraries(${Recipe_Name} PRIVATE Vulkan::Vulkan)`

**Comment by packt-pradeeps** [comment]
Thank you for highlighting this issue and the workaround.
